### ISSUE TITLE
geoalchemy and python 3

### ISSUE THREAD

**Issue by mese79** [geoalchemy/geoalchemy#41]
Hi
Does geoalchemy work with python 3.x ?
After i installed it, i've got this error on import:
```
>>> from geoalchemy import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mehdi/Programming/Python/virtualenvs/measurment-app/lib/python3.4/site-packages/GeoAlchemy-0.7.3.dev0-py3.4.egg/geoalchemy/__init__.py", line 2, in <module>
    from geoalchemy.base import *
  File "/home/mehdi/Programming/Python/virtualenvs/measurment-app/lib/python3.4/site-packages/GeoAlchemy-0.7.3.dev0-py3.4.egg/geoalchemy/base.py", line 7, in <module>
    from utils import from_wkt
ImportError: No module named 'utils'
```
I'm working with an oracle database, so i think geoalchemy is the only package that i can use. isn't it?
Thanks.

**Comment by mwiebusch78** [comment]
I had the same problem. I'm not a geoalchemy developer, but I got it running with the following modifications to the code:

1. In base.py change

     from utils import ...
     from functions import ...

to

    from geoalchemy.utils import ...
    from geoalchemy.functions import ...

2. In base.py change any mention of ColumnProperty.ColumnComparator to ColumnProperty.Comparator.

3. In geometry.py replace any calls to the has_key method with the corresponding 'in' expression.

**Comment by aqellez** [comment]
It still not working
